version: "3.8"
services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    networks:
      - app-network
  
  order-service:
    build: ./order-service
    ports:
      - "3004:3004"
    networks:
      - app-network
    depends_on:
      - user-service
      - product-service
      - cart-service

  cart-service:
    build: ./cart-service
    ports:
      - "3003:3003"
    networks:
      - app-network
  frontend-service:
    build: ./frontend-service
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - user-service
      - product-service
      - order-service
      - cart-service

networks:
  app-network:
    driver: bridge
